# Generated by Django 3.2.13 on 2023-01-23 16:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_missing_migrations'),
    ]

    operations = [
        migrations.AddField(
            model_name='repositories',
            name='date_created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]