name: codeStats
services:
  frontend:
    build:
      context: frontend
      target: development
    networks:
      - client-side
    ports:
      - 3000:3000
    volumes:
      - ./frontend/src:/code/src:ro

  backend:
    build:
      context: backend
      target: development
    ports:
      - "8000:8000"
    networks:
      - client-side
      - server-side
    volumes:
      - ./backend/codestatsapi:/code/codestatsapi
      - backend-cache:/code/target
    depends_on:
      - db
    env_file:
      - ./backend/.dev.env

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    networks:
      - server-side
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data

networks:
  client-side: {}
  server-side: {}

volumes:
  backend-cache: {}
  db-data: {}
