version: "3.9"

services:
  django:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - .:/backend
    env_file:
      - ./backend/.env
    command: gunicorn --bind 0.0.0.0:8000 codestatsapi.wsgi --timeout 100000000
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./postgres/.env
  react:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - API_SERVER=${ENV_API_SERVER}
    volumes:
      - react_static_volume:/usr/src/app/build/static
    ports:
      - 3000:3000
    env_file:
      - .env
    command: serve -s build -l 3000
    depends_on:
      - django

  nginx:
    restart: always
    build: ./nginx
    volumes:
      - .:/backend
      - /static:/static
    ports:
      - 80:80
    depends_on:
      - react

  redis:
    image: redis:alpine
    depends_on:
      - db

  grafana:
    image: grafana/grafana-oss
    ports:
      - 3001:3000
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    user: "104"

  celery:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: celery_codestats
    command: celery -A codestatsapi worker -l INFO
    volumes:
      - static-content:/usr/src/app/
    env_file:
      - ./backend/.env
    depends_on:
      - redis
      - django

volumes:
  postgres_data:
  django_static_volume:
  react_static_volume:
  celery_volume:
  static-content:
