version: "3.9"

volumes:
  postgres_data: {}
  postgres_data_backups: {}

services:
  django:
    restart: always
    build:
      context: ./codestatsapi
      dockerfile: ./compose/django/Dockerfile
    image: api_v1
    container_name: api_v1
    volumes:
      - ./codestatsapi:/codestatsapi
    depends_on:
      - postgres
    env_file:
      - ./codestatsapi/.envs/.django
      - ./codestatsapi/.envs/.postgres
    ports:
      - "8000:8000"
    command: /start

  postgres:
    restart: always
    build:
      context: ./codestatsapi
      dockerfile: ./compose/postgres/Dockerfile
    image: postgres_django
    container_name: postgres_django
    volumes:
      - postgres_data:/var/lib/postgresql/data:Z
      - postgres_data_backups:/backups:z
      
    env_file:
      - ./codestatsapi/.envs/.postgres

  react:
    build: ./dist
    ports:
      - "80:80"
    depends_on:
      - django
