{
 "title": "Codestats",
 "time": { "from": "2022-04-23T14:16:56.643Z", "to": "2023-01-26T19:54:10.630Z" },
 "templating": {
  "list": [
   {
    "name": "Repository",
    "query": "SELECT repo_name FROM api_repositories"
   },
   {
    "name": "Branch",
    "query": "SELECT api_branches.name FROM api_repositories INNER JOIN api_branches ON api_branches.repository_id = api_repositories.id \nWHERE repo_name = '$Repository' and iteration='$Iteration' GROUP BY api_branches.name ORDER BY api_branches.name "
   },
   {
    "name": "User",
    "query": "SELECT api_authors.name from api_commits\nINNER JOIN api_branches ON api_branches.id = api_commits.branch_id\nINNER JOIN api_authors ON api_authors.id = api_commits.author_id\nINNER JOIN api_repositories ON api_repositories.id = api_branches.repository_id\nWHERE repo_name = '$Repository'  AND api_branches.name = '$Branch'"
   },
   {
    "name": "Iteration",
    "query": "SELECT iteration FROM api_repositories \nWHERE repo_name = '$Repository'"
   }
  ]
 },
 "panels": [
  {
   "title": "Repo languages piechart",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT languages, SUM(percentage) FROM api_repolanguages \nINNER JOIN api_repositories ON api_repositories.id = api_repolanguages.repository_id\nWHERE repo_name = '$Repository' and api_repositories.iteration = $Iteration \nGROUP BY languages"
    }
   ]
  },
  {
   "title": "Commits per selected user and branch",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT api_authors.name, COUNT(api_commits.message) from api_commits\nINNER JOIN api_branches ON api_branches.id = api_commits.branch_id\nINNER JOIN api_authors ON api_authors.id = api_commits.author_id\nINNER JOIN api_repositories ON api_repositories.id = api_branches.repository_id\nWHERE api_branches.name = '$Branch' and api_repositories.repo_name = '$Repository' and api_repositories.iteration = $Iteration \nGROUP BY api_authors.name"
    }
   ]
  },
  {
   "title": "Commits per user",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT api_authors.name, COUNT(api_commits.message) from api_commits\nINNER JOIN api_branches ON api_branches.id = api_commits.branch_id\nINNER JOIN api_authors ON api_authors.id = api_commits.author_id\nINNER JOIN api_repositories ON api_repositories.id = api_branches.repository_id\nWHERE api_repositories.repo_name = '$Repository' and api_repositories.iteration = $Iteration \nGROUP BY api_authors.name"
    }
   ]
  },
  {
   "title": "Commits per selected User and Branch",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT api_commits.date, count(api_commits.date) from api_commits\nINNER JOIN api_branches ON api_branches.id = api_commits.branch_id\nINNER JOIN api_authors ON api_authors.id = api_commits.author_id\nINNER JOIN api_repositories ON api_repositories.id = api_branches.repository_id\nWHERE api_branches.name = '$Branch' and api_repositories.repo_name = '$Repository' and api_authors.name = '$User' and api_repositories.iteration = $Iteration \nGROUP BY api_commits.date"
    }
   ]
  },
  {
   "title": "Commits per branch",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT api_branches.name, COUNT(api_commits.message) from api_commits\nINNER JOIN api_branches ON api_branches.id = api_commits.branch_id\nINNER JOIN api_authors ON api_authors.id = api_commits.author_id\nINNER JOIN api_repositories ON api_repositories.id = api_branches.repository_id\nWHERE api_repositories.repo_name = '$Repository' and api_repositories.iteration = $Iteration \nGROUP BY api_branches.name"
    }
   ]
  },
  {
   "title": "Commits selected branch",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT api_commits.date, count(api_commits.date) from api_commits\nINNER JOIN api_branches ON api_branches.id = api_commits.branch_id\nINNER JOIN api_authors ON api_authors.id = api_commits.author_id\nINNER JOIN api_repositories ON api_repositories.id = api_branches.repository_id\nWHERE api_branches.name = '$Branch' and api_repositories.repo_name = '$Repository'\nGROUP BY api_commits.date"
    }
   ]
  },
  {
   "title": "Commits per date",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT\n  api_commits.date,\n  count(message)\nFROM api_repositories \nINNER JOIN api_authors ON api_authors.repository_id = api_repositories.id\nINNER JOIN api_commits ON api_commits.author_id = api_authors.id\nWHERE repo_name = '$Repository' AND $__timeFilter(date) and api_repositories.iteration = $Iteration \nGROUP BY api_commits.date"
    }
   ]
  },
  {
   "title": "Lines efected by branch and user",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "rawSql": "SELECT\n  api_authors.name, SUM(insertions) as insertions, SUM(deletions) as deletions, SUM(lines) as lines\nFROM api_changes\nINNER JOIN api_commits ON api_commits.id = api_changes.commit_id\nINNER JOIN api_branches ON api_branches.id = api_commits.branch_id\nINNER JOIN api_authors ON api_authors.id = api_commits.author_id\nINNER JOIN api_repositories ON api_repositories.id = api_branches.repository_id\nWHERE api_branches.name = '$Branch' and api_repositories.repo_name = '$Repository' and api_repositories.iteration = $Iteration \nGROUP BY api_authors.name"
    }
   ]
  },
  {
   "title": "Lines changed on Branch",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "rawSql": "SELECT\n  insertions, deletions, lines\nFROM api_changes\nINNER JOIN api_commits ON api_commits.id = api_changes.commit_id\nINNER JOIN api_branches ON api_branches.id = api_commits.branch_id\nINNER JOIN api_authors ON api_authors.id = api_commits.author_id\nINNER JOIN api_repositories ON api_repositories.id = api_branches.repository_id\nWHERE api_branches.name = '$Branch' and api_repositories.repo_name = '$Repository' and api_repositories.iteration = $Iteration \n"
    }
   ]
  }
 ]
}