# Generated by Django 4.0.4 on 2022-06-07 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Branches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('commits_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Repositories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Commits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('message', models.CharField(max_length=500)),
                ('edited_files', models.CharField(max_length=1000)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.authors')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.branches')),
            ],
        ),
        migrations.AddField(
            model_name='branches',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.repositories'),
        ),
        migrations.AddField(
            model_name='authors',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.repositories'),
        ),
    ]
