# Generated by Django 4.1.3 on 2022-11-12 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_emails'),
    ]

    operations = [
        migrations.AddField(
            model_name='repositories',
            name='url',
            field=models.CharField(default='asd', max_length=1000),
            preserve_default=False,
        ),
    ]
